### ISSUE TITLE
Add test suite setup and initial tests

### ISSUE THREAD

**Issue by mikeric** [attendease/attendease-js#5]
Need to get some automated tests in here. Because this project is open source, perhaps we can use [Travis](https://travis-ci.org/) or [Open Sauce](https://saucelabs.com/opensauce/)?

- [x] Use jasmine for test framework.
- [x] Use karma as the test runner.
- [x] Add a few initial tests.

**Comment by eddanger** [comment]
Travis setup would be nice.
